<?xml version="1.0" encoding="gbk"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
<bean id="billactionTotal" class="nc.pubapp.pade.platform.vo.BillactionTotal"><property name="actionList">
<list><bean class="nc.pubapp.pade.platform.vo.Billaction"><property name="action_type" value="30"/>
<property name="actionnote" value="删除"/>
<property name="actionstyle" value="3"/>
<property name="actiontype" value="DELETE"/>
<property name="constrictflag" value="false"/>
<property name="controlflag" value="false"/>
<property name="finishflag" value="false"/>
<property name="pk_billaction" value="0001ZZ1000000000N4SU"/>
<property name="pk_billtype" value="2011"/>
<property name="pk_billtypeid" value="0001ZZ1000000000N4ST"/>
</bean>
<bean class="nc.pubapp.pade.platform.vo.Billaction"><property name="action_type" value="31"/>
<property name="actionnote" value="保存"/>
<property name="actionstyle" value="1"/>
<property name="actiontype" value="SAVEBASE"/>
<property name="constrictflag" value="true"/>
<property name="controlflag" value="false"/>
<property name="finishflag" value="false"/>
<property name="pk_billaction" value="0001ZZ1000000000N4SV"/>
<property name="pk_billtype" value="2011"/>
<property name="pk_billtypeid" value="0001ZZ1000000000N4ST"/>
</bean>
</list>
</property>
<property name="billtypecode" value="2011"/>
<property name="pk_billtypeid" value="0001ZZ1000000000N4ST"/>
</bean>

</beans>